Linux build, windows init.sh fixes
dom96/choosenim pull request #238
Opened 2020-10-21 14:48 UTC by genotrance

2020-10-23 04:40 UTC, genotrance commented
@dom96 - PTAL

cc @alaviss

2020-10-23 09:22 UTC, genotrance commented
Still some issues, hold off on merge.

2020-10-23 20:00 UTC, genotrance commented
This is ready to go - please review and merge.

2020-10-24 18:17 UTC, dom96 requested changes
Why did you move the static build flags out of the .nims? I thought we agreed to have a flag that could be passed to ``nim`` for a static build, and just specify these flags in that config file behind a `-d:static` or something?

Since this is nimscript I think you could easily reuse that config for proxyexe and you wouldn't need this new `-d:skipBuild` flag which I'm also not a big fan of.

2020-10-24 19:43 UTC, genotrance commented
All such flags can be specified on the command line with - -passL, either with Nim or nimble. Why an extra flag?

-d:skipBuild was added to avoid building with the wrong flags or local testing. 

If you have better ideas for this, please suggest specifics. This took several hours of time to get right, it's not a two minute change. I also tested this with my travister matrix which tests normal builds that users would do locally.

https://travis-ci.org/github/genotrance/travister/builds/738344603

2020-10-25 10:20 UTC, dom96 commented
> All such flags can be specified on the command line with - -passL, either with Nim or nimble. Why an extra flag?

Because if I then want to locally create a static build then I need to copy and paste the flags manually from the CI scripts...

> If you have better ideas for this, please suggest specifics. This took several hours of time to get right, it's not a two minute change. I also tested this with my travister matrix which tests normal builds that users would do locally.

* Create a `proxyexe.nims` file in `choosenimpkg`:

```nim
when defined(staticBuild):
  putEnv("CC", "musl-gcc")
  switch("gcc.exe", "musl-gcc")
  switch("gcc.linkerexe", "musl-gcc")
  when not defined(OSX):
    switch("passL", "-static")
```

* In ``choosenim.nims``: ``import "choosenimpkg/proxyexe.nims"`` (I'm not sure if this works, but AFAIK that is the point of .nims, so it would be pretty ridiculous if there wasn't a way to do it, maybe you need to wrap that stuff in a proc and call it from both the ``proxyexe.nims`` and the ``choosenim.nims``)

* In CI just pass the `-d:staticBuild` flag
* In switcher.nim:

```nim
when defined(staticBuild):
  cmd.add("-d:staticBuild")
```

(As an aside, I'm not sure where the new flags you've added for Linux/Windows belong (-lpthread/-lws2_32). If they're also related to staticBuild then they should go under that ``when`` otherwise they can stay in the .nims. Please do explain what they're for though.)

2020-10-26 20:52 UTC, genotrance commented
@dom96 - PTAL - ready to go.

Also, please migrate from travis-ci.org to travis-ci.com so that build times improve. Should take 5 minutes to migrate your repos over.

2020-10-28 19:59 UTC, dom96 approved these changes
Much better, thank you! Please resolve my comment before merging.

2020-10-28 19:59 UTC, dom96 commented on src/choosenimpkg/switcher.nim
> +    cmd.add " -d:danger"
Please don't do that. Release is fine...

2020-10-28 20:04 UTC, genotrance commented on src/choosenimpkg/switcher.nim
> +    cmd.add " -d:danger"
I made it danger cause the shims get called hundreds of times and are simple code. Seemed worth it to me to optimize them a bit more.

2020-10-28 21:52 UTC, dom96 commented on src/choosenimpkg/switcher.nim
> +    cmd.add " -d:danger"
I doubt it'll have a significant impact on the performance, but it may have a big impact on our ability to understand what's breaking.

2020-10-29 17:49 UTC, merged